### ISSUE TITLE
Still getting grunt 0.4 as peerDependency

### ISSUE THREAD

**Issue by hugoduraes** [jamesdbloom/mockserver-grunt#11]
I installed `mockserver-grunt@1.0.30` and I'm still getting `grunt@~0.4` as a peerDependency. I believe it's because the version was not bumped after the changes introduces by this https://github.com/jamesdbloom/mockserver-grunt/commit/e81d8cf3d9bc2fe49bba86cdf8b168fa37fbe58c merge.

Can you please create a new release that includes these changes?

**Comment by jamesdbloom** [comment]
this is now fixed, please upgrade to 1.0.31

**Comment by hugoduraes** [comment]
Thank you!
