### ISSUE TITLE
stop_mockserver ignores port configuration

### ISSUE THREAD

**Issue by faredis** [jamesdbloom/mockserver-grunt#8]
when I run the server via grunt and want to keep it active i am doing:
`grunt start_mockserver`
Then when finished I expected to be able to do:
`grunt stop_mockserver`
but it fails as it defaults to port 80.

stop_mockserver ignores the port settings unless run in the same task group within grunt like the tests are so the test port is still defined.

**Comment by romansavchenko** [comment]
Bump any news on this?

**Comment by jamesdbloom** [comment]
this is now fixed in version 1.0.32
